/*******************************************************************************
 * Copyright (c) 2011 Agnity, Inc. All rights reserved.
 * <p>
 * This is proprietary source code of Agnity, Inc.
 * <p>
 * Agnity, Inc. retains all intellectual property rights associated
 * with this source code. Use is subject to license terms.
 * <p>
 * This source code contains trade secrets owned by Agnity, Inc.
 * Confidentiality of this computer program must be maintained at
 * all times, unless explicitly authorized by Agnity, Inc.
 *******************************************************************************/

package com.agnity.ph.common.enums;

import static com.agnity.mphutility.enums.DataAttributeType.STRING;
import static com.agnity.ph.common.enums.PersistanceType.NON_PERSISTABLE;
import static com.agnity.ph.common.enums.PersistanceType.PERSISTABLE;

import org.omg.PortableInterceptor.NON_EXISTENT;


/**
 * Created by ankitsinghal on 12/02/16.
 * This is a interface used for defining names for leg attributes used for a
 * call . All the persistable properties are marked as P_ and non-persistable
 * properties are marked as NP_
 */
public enum LegDataAttributes {

	/*
	 * Leg state
	 */
	P_LEG_SIP_STATE(PERSISTABLE),

	/*
	 * Session ID of this this leg[orig/term]
	 */
	P_SESSION_ID(PERSISTABLE),

	/*
	 * Session ID of IVR connected to this leg
	 */
	P_IVR_SESSION_ID(PERSISTABLE),

	/*
	 * Call Id of this sip session
	 */
	P_CALL_ID(PERSISTABLE),

	/*
	 * TRUE if no-answer timeout has been received on this leg. mPH sets this
	 * flag on term legData if no-answer timeout happens on term leg. After this
	 * PH sends cancel of term leg. And after receiving 487 response from term
	 * mPh checks if this flag is present in term LegData if yes then then 487
	 * is received for cancel send by mPH
	 */
	P_NO_ANSWER_TIMEOUT_IND(PERSISTABLE),
	/*
	 * Duration of no-answer timer in milli-seconds timer for TERM leg only.
	 * Value of this property is Integer
	 */
	NP_NO_ANSWER_TIMER_DURATION(NON_PERSISTABLE),

	/*
	 * Sip Response code to be sent on this sip session. Set SIP cause
	 * code as its value. Its value is of Integer Type
	 */
	P_CAUSE_CODE(PERSISTABLE),

	/*
	 * If TRUE then there is some outstanding INVITE for this leg. If not
	 * present then there is no outstanding INVITE on this leg
	 */
	P_INVITE_PENDING_TRANS(PERSISTABLE),

	/*
	 * Valud of this key is SipServletResponse [200 OK message] pending to be
	 * senn on this leg
	 */
	P_PENDING_SUCC_RESP(PERSISTABLE),

	/*
	 * Value of this key is provisional response pending to be sent on this leg
	 */
	NP_PENDING_PROV_RESP(PERSISTABLE),  //FIXME: Remove NP from EnumName

	/*
	 * Value of this key is PRACK pending to be sent on this leg
	 */
	NP_PENDING_PRACK(PERSISTABLE), //FIXME: Remove NP from EnumName

	/*
	 * Value of this field is ACK that is pending to be sent on this leg.
	 */
	P_PENDING_ACK(PERSISTABLE),

	/*
	 * LAST and current SDP received on this sip session
	 */
	P_LAST_RECEIVED_SDP(PERSISTABLE),

	P_CURRENT_RECEIVED_SDP(PERSISTABLE),

	/*
	 * LAST SDP sent on this sip session
	 */
	P_LAST_SENT_SDP(PERSISTABLE),

	/*
	 * Name of session refresh timer for this leg
	 */
	P_SESSION_REFRESH_TIMER_NAME(PERSISTABLE),

	/*
	 * Name of timer which is started by mPH if it receives 491 response for
	 * Re-INVITE
	 */
	P_INV_PENDING_TRANS_TIMER_NAME(PERSISTABLE),

	/*
	 * If true then offer is received from this leg which has not answered yet
	 */
	NP_IS_OFFER_RECEIVED(NON_PERSISTABLE),

	/*
	 * If true then offer has been sent on this leg
	 */
	NP_IS_OFFER_SENT(NON_PERSISTABLE),

	/*
	 * If true then CANCEL is received from this leg
	 */
	P_IS_CANCEL_RECEIVED(PERSISTABLE),

	/*
	 * If true then mPH has sent UPDATE with unicast SDP on this leg
	 */
	NP_IS_UNICAST_SDP_UPDATE(NON_PERSISTABLE),

	/*
	 * Represents connection type for current legData
	 */
	P_CONNECTION_TYPE(PERSISTABLE),

	/*
	 * Number of times IVR is connected to this leg
	 */
	P_IVR_CONNECTION_COUNT(PERSISTABLE),

	/*
	 * TRUE if SDP has already been sent on this leg
	 */
	NP_IS_SDP_SENT(NON_PERSISTABLE),

	/*
	 * TRUE if mPH has sent 180 response on this leg
	 */
	NP_IS_RINGING_SENT(NON_PERSISTABLE),

	/*
	 * Value of Session-Expires header from INCOMING session refresh INVITE
	 */
	P_SESSION_EXPIRE_TIME(PERSISTABLE),
	/*
	 * Value of Min-Se header from INCOMING session refresh INVITE
	 */
	P_SESSION_EXPIRE_MIN_SE(PERSISTABLE),
	/*
	 * Time in ms when session refresh timer for this leg started
	 */
	P_SESSION_EXPIRE_TIMER_START_TIME(PERSISTABLE),

	/*
	 * This is the CANCEL/BYE or error message received from the peer leg. This
	 * message can be used 1. If error response is received from peer leg then
	 * the Current leg isalso disconnected with same SIP error code. 2.
	 * PEER_LEG_CANCEL_BYE_ERR_MSG can also be used if any headers from
	 * PEER_LEG_CANCEL_BYE_ERR_MSG are required to be copied in current leg
	 * ERROR/BYE response.
	 */
	P_PEER_LEG_CANCEL_BYE_ERR_MSG(PERSISTABLE),

	/*
	 * Calling Party
	 */
	P_CALLING_PARTY_FROM_HEADER(PERSISTABLE),
	P_CALLING_PARTY_PAI_HEADER(PERSISTABLE),
	/*
	 * Calling Party
	 */
	P_CALLING_PARTY(PERSISTABLE),

	/*
	 *Calling Destination Number
	 * */
	P_CALLING_DN(PERSISTABLE),


	/*
	 * Calling Party
	 */
	P_CALLING_PARTY_TEL(PERSISTABLE),

	/*
	 * Called Party
	 */
	P_CALLED_PARTY(PERSISTABLE),
	P_CALLED_PARTY_NOA(PERSISTABLE),

	/*
	 * IDP Called Party
	 */
	P_IDP_CALLED_PARTY(PERSISTABLE),

	/*
	 * CPC
	 */
	P_CPC_FROM_HEADER(PERSISTABLE),
	P_CPC_PAI_HEADER(PERSISTABLE),
	P_CPC_PAI_TEL_HEADER(PERSISTABLE),

	/*
	 * Contractor Number
	 */
	P_CONTRACTOR_NUMBER(PERSISTABLE),

	/*
	 * Dialed Digits
	 */
	P_DIALED_DIGITS(PERSISTABLE),

	/*
	 * Destination number
	 */
	P_DESTINATION_NUMBER(PERSISTABLE),
	P_DESTINATION_NUMBER_NOA_INT(PERSISTABLE),
	P_DESTINATION_NUMBER_NUM_PLAN_INT(PERSISTABLE),
	P_DESTINATION_NUMBER_ADDR_PRSNT_REST_INT(PERSISTABLE),

	/*
	 * If TRUE then mPH has replicated app-session on receiving first
	 * provisional response from this leg. At present this feature is
	 * implemented for term leg only
	 */
	NP_IS_PROV_RESP_REPLICATED(NON_PERSISTABLE),

	/*
	 * TRUE if chargeable announcement should be played
	 */
	NP_IS_CHARGEABLE_ANN(NON_PERSISTABLE),

	/*
	 * Ann Spec to play ann on this leg
	 */
	NP_ANN_SPEC(NON_PERSISTABLE),

	/*
	 * Conference Spec
	 */
	NP_CONF_SPEC(NON_PERSISTABLE),

	/*
	 * Record Spec
	 */
	NP_REC_SPEC(NON_PERSISTABLE),
	/*
	 * IP where message needs to be sent
	 */
	P_REMOTE_IP(PERSISTABLE),

	/*
	 * Port where message needs to be sent . Type should be integer
	 */
	P_REMOTE_PORT(PERSISTABLE),

	/*
	 * Reason received in stop recording response from IVR
	 */
	NP_STOP_RECORDING_REASON(NON_PERSISTABLE),
	/*
	 * In case of play and record, mPH sets the length of recording on callData
	 * object
	 */
	NP_RECORDING_LENGTH(NON_PERSISTABLE),

	/*
	 * In case of play and collect, mPH sets the collected digits on callData
	 * object
	 */
	P_COLLECTED_DIGITS(PERSISTABLE),

	/*
	 * VXML file path on local SAS machine
	 */
	NP_VXML_FILE_PATH(NON_PERSISTABLE),

	/*
	 * Will be filled up only DNIS is enabled. Respective handler (sip and SS7)
	 * will check for this attribute while sending terminating invite
	 */
	NP_ORIG_CALLED_PARTY_NUMBER(PERSISTABLE), //FIXME: Remove NP from EnumName

	/*
	 * Diversion reason. This shall be used while sending orig called party
	 * number
	 */
	NP_DIVERSION_REASON(PERSISTABLE),  //FIXME: Remove NP from EnumName

	/*
	 * Content of reason header in case of error messages. Syntax: Reason: SIP;
	 * text="Orig call screening failure"
	 */
	P_REASON(PERSISTABLE),

	/*
	 * SS7 specific Attributes in Leg
	 */
	P_DIALOG_ID(PERSISTABLE),

	/*
	 * DPs armed by service.
	 */
	P_ERB_SET(PERSISTABLE),
	P_ERB_CAUSE_CODE(PERSISTABLE),

	/*
	 * Dialogue Portion received in incoming DIalogue
	 */
	P_DIALOG_PORTION(PERSISTABLE),
	/*
	 * Activity COntext Version
	 */
	P_ACTIVITY_CONTEXT_VERSION(PERSISTABLE),

	/*
	 * Signaling Point Code, Originating Point Code and SCCP address received in
	 * incoming Initial DP
	 */
	P_SPC(PERSISTABLE),

	P_OPC(PERSISTABLE),

	P_SUA(PERSISTABLE),
	/*
	 * Last rxed Invoke Id
	 */
	P_LAST_RX_INVOKE_ID(PERSISTABLE),

	P_OUTGOING_LAST_RX_INVOKE_ID(PERSISTABLE),

	P_LEG_SS7_STATE(PERSISTABLE),

	P_CORRELATION_EXPIRY_TIME(PERSISTABLE),

	P_AT_EXPIRY_TIME(PERSISTABLE),

	P_CORRELATED_ORIG_LEG_CLEANUP_TIME(PERSISTABLE),

	P_CORRELATED_ORIG_LEG_CLEANUP_IND(PERSISTABLE),

	NP_ERB_TIMEOUT_TIMER_DURATION(NON_PERSISTABLE),

	P_IMSI(PERSISTABLE),

	P_MSC_ADDR(PERSISTABLE),

	P_TIMEZONE(PERSISTABLE),

	P_CALL_REF_NUM(PERSISTABLE),

	NP_EVENT_TYPE_BCSM(NON_PERSISTABLE),

	P_BEAR_CAP(PERSISTABLE),

	P_LOCATION_NUMBER(PERSISTABLE),

	P_LOCATION_INFO(PERSISTABLE),

	P_CALL_RESULT(PERSISTABLE),

	P_FCI_BILLING_CHARACTERISTICS(PERSISTABLE),

	P_CURRENT_RECEIVED_ANM(PERSISTABLE),

	P_OTHER_LEG_ERR_BYE_CAN_MSG(PERSISTABLE),

	P_SIGNALING_TYPE_KEY(PERSISTABLE),

	P_IS_RINGING_SENT(PERSISTABLE),

	P_IS_ACM_SENT(PERSISTABLE),

	P_IS_BLEG_ACM_CPG_SENT(PERSISTABLE),

	NP_CUSTOM_HEADERS_MAP(NON_PERSISTABLE),

	P_LEG_MAP_STATE(PERSISTABLE),

	P_FROM_DOMAIN(PERSISTABLE),

	P_SWITCH_ID(PERSISTABLE),

	P_TRUNK_GRP_ID(PERSISTABLE),

	P_CIC(PERSISTABLE),

	P_NOA(PERSISTABLE),

	P_CHARGE_INFO(PERSISTABLE),

	P_JIP(PERSISTABLE),

	P_RN(PERSISTABLE),

	P_NPDI(PERSISTABLE),

	P_PENDING_REFER(PERSISTABLE),

	P_CPC(PERSISTABLE),

	NP_CALLING_PARTY_OVERRIDE(NON_PERSISTABLE),

	/**
	 * EQS is equivalent to CRE
	 */
	NP_EQS_ERR_RESPONSE_ROUING_MAP(NON_PERSISTABLE),

	//Added for MAP
	NP_ATI_REQ(NON_PERSISTABLE),
	NP_ATI_RES(NON_PERSISTABLE),

	//CS NETWORK
	NP_ATI_SUBSCRIBER_STATE(NON_PERSISTABLE),
	NP_ATI_AGE_OF_LOCATION_INFORMATION_CS(NON_PERSISTABLE),
	NP_ATI_VLR_NUMBER(NON_PERSISTABLE),
	NP_ATI_LOCATION_NUMBER(NON_PERSISTABLE),
	NP_ATI_MSC_NUMBER(NON_PERSISTABLE),
	NP_ATI_CELL_GLOB_ID_OR_SERV_AREA_OR_LAI_CONSTR(NON_PERSISTABLE),
	NP_ATI_CELLGIDORSAIORLAI_FLAG(NON_PERSISTABLE),
	// PS NETWORK	
	NP_ATI_ET_PS_SUBSCRIBER_STATE_lOCATION_RESP(NON_PERSISTABLE),
	NP_ATI_LOCATION_INFORMATION_GPRS(NON_PERSISTABLE),
	NP_ATI_APNU(NON_PERSISTABLE),
	NP_ATI_PDPST(NON_PERSISTABLE),
	NP_ATI_RESULT_CODE(NON_PERSISTABLE),

	// LTE NETWORK
	NP_UDA_EUTRAN_CELL_GLOBAL_ID(NON_PERSISTABLE), 
	NP_UDA_TRACKING_AREA_ID(NON_PERSISTABLE),
	NP_UDA_MME_NAME(NON_PERSISTABLE), 
	NP_UDA_AGE_OF_LOCATION_INFORMATION(NON_PERSISTABLE),
	NP_UDA_RESULT_CODE(NON_PERSISTABLE),

	NP_ATSI_REQ(NON_PERSISTABLE),
	NP_ATSI_RES(NON_PERSISTABLE),

	NP_ATM_REQ(NON_PERSISTABLE),
	NP_ATM_RES(NON_PERSISTABLE),

	NP_SRI_REQ(NON_PERSISTABLE),
	NP_SRI_RES(NON_PERSISTABLE),

	NP_NSDM_REQ(PERSISTABLE),  //FIXME: Remove NP from EnumName
	NP_NSDM_RES(NON_PERSISTABLE),

	P_HLR_SUA(PERSISTABLE),

	NP_GW_POOL_ID(NON_PERSISTABLE),

	NP_LAST_GW_ID(NON_PERSISTABLE),

	NP_SEND_DIVERSION_HDR(PERSISTABLE), //FIXME: Remove NP from EnumName

	P_CPC_ORIGINAL(PERSISTABLE),

	NP_TRANSFER_KEY(NON_PERSISTABLE),

	NP_OUTBOUND_GW_ADDR(NON_PERSISTABLE),

	NP_SEND_ORIG_TO_HDR(NON_PERSISTABLE),

	NP_EQS_RETRY_COUNT(NON_PERSISTABLE),

	NP_REFER_TO_HEADER(NON_PERSISTABLE),

	P_PENDING_UPDATE(PERSISTABLE),

	NP_REMOVE_PRIVACY_HEADER(NON_PERSISTABLE),

	P_LEG_CURRENT_ACTION(PERSISTABLE),

	P_100_REL_RETRY_TIMER_NAME(PERSISTABLE),

	REL_RETRY_PROV_RESPONSE(PERSISTABLE),

	P_APP_SPECIFIC_DATA(PERSISTABLE),

	NP_APP_SPECIFIC_DATA(NON_PERSISTABLE), 

	NP_SEND_DNIS_IN_SIPT(NON_PERSISTABLE), 

	NP_TRUNK_GROUP(NON_PERSISTABLE), 

	NP_TRUNK_GROUP_CONTEXT(NON_PERSISTABLE),

	NP_REDIRECT_ADDRESS(NON_PERSISTABLE), 

	HOLD_ON_MUSIC_PLAY(PERSISTABLE), 

	DESTINATION_LIST(NON_PERSISTABLE), 

	INVITE_ATTRIBUTES(NON_PERSISTABLE), 

	FORKING_INVITE_ATTRIBUTES_LIST(NON_PERSISTABLE),

	APP_SESSION_ID(PERSISTABLE),

	TRANSFER_MODIFIED_URI(PERSISTABLE),

	/*
	 * field used by application to define IPRoutingAddress used in Connect to Resource
	 * INAP message. 
	 */
	CTR_RESOURCE_ADDRESS(NON_PERSISTABLE),

	// fields specific to bearer capability 
	// transfer Rate and transfer capability
	P_TRANSFER_RATE(PERSISTABLE),
	P_TRANSFER_CAPABILITY (PERSISTABLE),

	// fields specifying monitor mode of ERB set by application. 
	P_ERB_ROUTESELECTFAILURE_MODE(PERSISTABLE),
	P_ERB_BUSY_MODE(PERSISTABLE),
	P_ERB_NO_ANSWER_MODE(PERSISTABLE), 
	P_AT_ACK_EXPIRY_TIME(PERSISTABLE),

	// AIN specific attributes 
	P_CHARGE_NUMBER(PERSISTABLE), 
	PI_CARRIER(NON_PERSISTABLE),   // carrier for provide Instruction
	PI_AMA_CALLTYPE(NON_PERSISTABLE), 
	PI_SERVICE_FEATURE_ID(NON_PERSISTABLE),
    P_FEATURE_TYPE_INDICATOR(PERSISTABLE),//TR533
    P_NO_ANSWER_TIME(PERSISTABLE),//TR533
    P_SPECIAL_ROUTING(PERSISTABLE),//TR533
	P_CARRIER(PERSISTABLE),
	P_CARRIER_SELECTION_CODE(PERSISTABLE),
	P_ALT_CARRIER(PERSISTABLE),
	P_SECOND_ALT_CARRIER(PERSISTABLE),
	P_COLLECTED_ADDRESS_INFO(PERSISTABLE), 
	P_CHARGE_PARTY_STATION_TYPE(PERSISTABLE), 
	P_REDIRECTING_PARTY_ID(PERSISTABLE), 
	P_REDIRECTION_INFO(PERSISTABLE),
	P_REDIRECTING_PARTY_ID_NOA(PERSISTABLE),
	P_REDIRECTING_PARTY_ID_NP(PERSISTABLE),
	P_TRIGGER_CRITERIA(PERSISTABLE), 
	P_USER_ID(PERSISTABLE), 
	P_AMASLPID(PERSISTABLE), 
	P_AMALINENUMBER(PERSISTABLE), 
	P_AMALINENUMBER2(PERSISTABLE), 
	P_AMA_ALT_BILLING_NUMBER(PERSISTABLE), 
	P_OVERFLOW_BILLING_IND(PERSISTABLE), 
	P_PRIMARY_TRUNK_GROUP(PERSISTABLE), 
	P_ALT_TRUNK_GROUP(NON_PERSISTABLE),
	P_SECOND_ALT_TRUNK_GROUP(NON_PERSISTABLE),
	P_PRIMARY_BILLING_IND (PERSISTABLE),
	P_ACCESS_CODE(PERSISTABLE), 
	P_OUTPULSE_NUM(PERSISTABLE),
	P_ALT_OUTPULSE_NUM(PERSISTABLE),
	P_SECOND_ALT_OUTPULSE_NUM(PERSISTABLE),
	P_LATA(PERSISTABLE),
	NP_PRIVACY_HEADER(NON_PERSISTABLE),
	NP_OUT_RES_PRIORITY_HEADER(NON_PERSISTABLE),
	NP_SEND_FORWARD_CALL_FOR_TERM_ATTEMPT(NON_PERSISTABLE),
	P_AMA_BUSINESS_CUSTOMER_ID(PERSISTABLE),

	// MRS
	P_MRS_RELAY(PERSISTABLE),

	// SIP ISUP SUB ADDRESS
	P_CALLING_ISUB(PERSISTABLE),
	P_CALLED_ISUB(PERSISTABLE),
	P_SCCP_REMOTE_SUB_SYSTEM_NUM(PERSISTABLE),
	P_SCCP_REMOTE_CALLED_NUMBER_TT(PERSISTABLE),
	P_OUT_CALLING_ISUB(PERSISTABLE),
	P_OUT_CALLED_ISUB(PERSISTABLE),

	P_HISTORY_INFO(PERSISTABLE), NP_PENDING_PRACK_SUCCESS(NON_PERSISTABLE),

	// AIN specific 
	P_CLG_PRESENTATION_RESTRICTED(PERSISTABLE),
	NP_AIN_SEND_NOTIFICATION(NON_PERSISTABLE),
	P_AMADIGITSDIALEDWC1(PERSISTABLE),
	P_AMADIGITSDIALEDWC2(PERSISTABLE),
	P_AMADIGITSDIALEDWC3(PERSISTABLE),
	P_AMADIGITSDIALEDWC4(PERSISTABLE),
	P_AMADIGITSDIALEDWC5(PERSISTABLE), 
	P_GENERIC_ADDR_DIALED_NUM(PERSISTABLE),
	P_GENERIC_ADDR_DESTINATION_NUM(PERSISTABLE),
	P_RC_CAUSE(PERSISTABLE), // resource clear cause. 
	P_CALL_INFO_FRM_R_TYPE(PERSISTABLE), //Call info from resource Resource Type
	P_STR_PRI_NUMBER(PERSISTABLE),       // Destination address in STR
	P_DISPLAY_TEXT_CLG_NAME(PERSISTABLE), // Calling party Name
	P_DISPLAY_TEXT_CLG_ADDR(PERSISTABLE), // Calling Party Address
	P_DISPLAY_TEXT_CLD_NAME(PERSISTABLE), // Called party Name
	P_DISPLAY_TEXT_CLD_ADDR(PERSISTABLE), // Called Party Address 
	P_ECHO_DATA(PERSISTABLE),			  // Echo Data

	//LIDB Query Parameter
	P_LIDB_QUERY_TYPE(PERSISTABLE),

	//PSX related keyword
	P_PSX_SSN(PERSISTABLE),
	P_PSX_RN(PERSISTABLE),
	P_PSX_DPC(PERSISTABLE),
	P_PSX_SPID(PERSISTABLE),
	P_PSX_IS_PORTED(PERSISTABLE),
	P_PSX_QTYPE(PERSISTABLE),
	P_PSX_UREP(PERSISTABLE),
	P_PSX_UCAT(PERSISTABLE),//The application <App NAME> specific query can be CLASS, LIDB, CNAM and ISVM.
	//BNS Query Parameter
	BNS_BILLING_NUM(PERSISTABLE),
	BNS_O_PRIMARY_SERVICE_REQUESTER(PERSISTABLE),
	BNS_O_PSRID_TYPE(PERSISTABLE),
	BNS_O_SECONDARY_SERVICE_REQUESTER(PERSISTABLE),
	BNS_O_SSRID_TYPE(PERSISTABLE),
	//BNSQuery Response Variables
	P_BNS_M_COMPANY_ID(PERSISTABLE),
	P_BNS_M_RECORD_STATUS_INDICATOR(PERSISTABLE),
	P_BNS_M_COLLECT_ACCEPTANCE_INDICATOR(PERSISTABLE),
	P_BNS_M_THIRD_NUMBER_ACCEPTANCE_INDICATOR(PERSISTABLE),
	P_BNS_M_TREATMENT_INDICATOR(PERSISTABLE),
	P_BNS_M_SERVICE_OR_EQUIPMENT_INDICATOR(PERSISTABLE),
	P_BNS_M_INTERCEPT_INDICATOR(PERSISTABLE),
	P_BNS_M_IC_INDICATOR_APIC(PERSISTABLE),
	P_BNS_M_IC_INDICATOR_PPIC(PERSISTABLE),
	P_BNS_M_IC_INDICATOR_PINC(PERSISTABLE),
	P_BNS_O_RAO_DIGIT(PERSISTABLE),
	P_BNS_O_PRIM_PREF_IC_DIGIT_IDENTIFIER(PERSISTABLE),
	P_BNS_O_ALT_PREF_IC_DIGIT_IDENTIFIER(PERSISTABLE),
	P_BNS_O_PREF_INC_DIGIT_IDENTIFIER(PERSISTABLE),
	P_BNS_O_REF_NUM(PERSISTABLE),
	P_BNS_O_REF_NUM_TYPE(PERSISTABLE),
	P_BNS_O_ACC_OWNER(PERSISTABLE),
	P_BNS_O_BILING_SER_PROV(PERSISTABLE),
	P_BNS_O_ACG_BILLED_NUMBER(PERSISTABLE),

	//TLNSQuery Request Variables
	TLNS_BILLING_NUM(PERSISTABLE),
	//TLNSQuery Response Variables
	P_TLNS_M_COMPANY_ID(PERSISTABLE),
	P_TLNS_M_RECORD_STATUS_INDICATOR(PERSISTABLE),
	P_TLNS_M_TERMINATING_LINE_INDICATORS(PERSISTABLE),
	P_TLNS_M_MESSAGE_DELIVERY_INDICATOR(PERSISTABLE),
	P_TLNS_M_OPERATOR_VERIFICATION_INTERRUPT_IND(PERSISTABLE),
	P_TLNS_M_NONPUBLISHED_NUMBER_CALLBACK_IND(PERSISTABLE),
	P_TLNS_M_TREATMENT_INDICATOR(PERSISTABLE),
	P_TLNS_M_SERVICE_OR_EQUIPMENT_INDICATOR(PERSISTABLE),
	P_TLNS_M_INTERCEPT_INDICATOR(PERSISTABLE),
	P_TLNS_M_IC_INDICATOR_APIC(PERSISTABLE),
	P_TLNS_M_IC_INDICATOR_PPIC(PERSISTABLE),
	P_TLNS_M_IC_INDICATOR_PINC(PERSISTABLE),
	P_TLNS_O_PRIM_PREF_IC_DIGIT_IDENTIFIER(PERSISTABLE),
	P_TLNS_O_ALT_PREF_IC_DIGIT_IDENTIFIER(PERSISTABLE),
	P_TLNS_O_PREF_INC_DIGIT_IDENTIFIER(PERSISTABLE),
	P_TLNS_O_REF_NUM(PERSISTABLE),
	P_TLNS_O_REF_NUM_TYPE(PERSISTABLE),
	P_TLNS_O_ACG_CALLED_NUMBER(PERSISTABLE),
	//CC1,CC2 Query Parameter
	CC1_BILLING_NUM(PERSISTABLE),
	CC1_BILLING_NUM_TYPE(PERSISTABLE),
	CC1_PIN(PERSISTABLE),
	CC2_BILLING_NUM(PERSISTABLE),
	CC2_BILLING_NUM_TYPE(PERSISTABLE),
	CC2_PIN(PERSISTABLE),
	CC_O_PRIMARY_SERVICE_REQUESTER(PERSISTABLE),
	CC_O_PSRID_TYPE(PERSISTABLE),
	CC_O_SECONDARY_SERVICE_REQUESTER(PERSISTABLE),
	CC_O_SSRID_TYPE(PERSISTABLE),
	//CCQuery Response Variables
	P_CC_COMPANY_ID(PERSISTABLE),
	P_CC_RECORD_STATUS_INDICATOR(PERSISTABLE),
	P_CC_CCSAN(PERSISTABLE),
	P_CC_PIN_RESTRICTION_INDICATOR(PERSISTABLE),
	P_CC_IC_INDICATOR_PPIC(PERSISTABLE),
	P_CC_IC_INDICATOR_APIC(PERSISTABLE),
	P_CC_IC_INDICATOR_PINC(PERSISTABLE),
	P_CC_RAO_DIGIT(PERSISTABLE),
	P_CC_ACC_OWNER(PERSISTABLE),
	P_CC_BILING_SER_PROV(PERSISTABLE),
	P_CC_PRIMARY_PREFERRED_IC(PERSISTABLE),
	P_CC_ALTERNATE_PREFERRED_IC(PERSISTABLE),
	P_CC_PREFERRED_INC(PERSISTABLE),
	P_CC_TRUE_BILLING_NUMBER(PERSISTABLE),
	P_CC_CCAN_SERVICE_DENIAL_INDICATOR(PERSISTABLE),
	P_CC_PIN_SERVICE_DENIAL_INDICATOR(PERSISTABLE),
	P_CC_PIN(PERSISTABLE),
	P_CC_MATCH(PERSISTABLE), 
	P_CC_O_ACG_BILLED_NUMBER(PERSISTABLE),
	//GN Query specific Attributes
	P_GN_M_GENERIC_NAME(PERSISTABLE),
	P_GN_M_GENERIC_NAME_AVAILABILITY(PERSISTABLE),
	P_GN_M_GENERIC_NAME_PRESENTATION(PERSISTABLE),
	P_GN_M_CALLING_PARTY(PERSISTABLE),
	P_GN_M_ACG_DURATION(PERSISTABLE),
	P_GN_M_ACG_GAP(PERSISTABLE),
	P_GN_IS_ACG_PARAM_PRESENT(PERSISTABLE),
	P_GN_O_DIALTONE_SERVICE(PERSISTABLE),
	P_GN_O_DTSRID_TYPE(PERSISTABLE),
	P_GN_O_BUSINESS_GROUP_ID(PERSISTABLE),

	//InterceptQuery Response Variables
	P_INTRCPT_M_COMPANY_ID(PERSISTABLE),
	P_INTRCPT_M_RECORD_STATUS_INDICATOR(PERSISTABLE),
	P_INTRCPT_M_INTERCEPT_INDICATOR(PERSISTABLE),
	P_INTRCPT_O_REF_NUM(PERSISTABLE),
	P_INTRCPT_O_REF_NUM_TYPE(PERSISTABLE),
	P_INTERCEPT_O_ACG_CALLED_NUMBER(PERSISTABLE),
	//ICDC query request variable
	ICDC_M_BILLING_NUM(PERSISTABLE),
	ICDC_M_CARRIER_ID(PERSISTABLE),
	//ICDC query response variable
	P_ICDC_ICDR(PERSISTABLE),
	P_ICDC_O_ACG_BILLED_NUMBER(PERSISTABLE),
	//Error Handling Attributes
	P_APP_ERR_CODE_IDENTIFIER(PERSISTABLE),
	P_APP_ERR_CODE(PERSISTABLE),
	P_APP_ERR_PROBLEM_DATA(PERSISTABLE),

	//ACB Query
	ACB_DESTINATION_NUM(PERSISTABLE),

	ENUM_NUMBER_QUERIED(PERSISTABLE), 
	ENUM_RESULT_LIST(PERSISTABLE), 
	ENUM_REQUEST_RECEIVED(PERSISTABLE), 
	ENUM_RESULT_RECORDS(NON_PERSISTABLE), 
	ENUM_KEY(NON_PERSISTABLE),
	ENUM_AUS(NON_PERSISTABLE),

	ENUM_CNAMSTRING (NON_PERSISTABLE), 
	ENUM_CNAM_UNAVAILABLE (NON_PERSISTABLE), 
	ENUM_CNAM_MESSAGE (NON_PERSISTABLE),
	ENUM_SERVICE_TYPE(NON_PERSISTABLE),

	//OLNS Query specific Attributes
	P_OLNS_O_BILLING_NUM(PERSISTABLE),
	OLNS_O_PRIMARY_SERVICE_REQUESTER(PERSISTABLE),
	OLNS_O_PSRID_TYPE(PERSISTABLE),
	P_OLNS_M_TREATMENT_INDICATOR(PERSISTABLE), 
	P_OLNS_M_SERV_EQP_INDICATOR(PERSISTABLE), 
	P_OLNS_M_ORIG_IC_INDICATOR_OIC(PERSISTABLE),
	P_OLNS_M_ORIG_IC_INDICATOR_OINC(PERSISTABLE),
	P_OLNS_M_ORIG_BILL_SER_IND1(PERSISTABLE),
	P_OLNS_M_ORIG_BILL_SER_IND2(PERSISTABLE),
	P_OLNS_M_ORIG_BILL_SER_IND3(PERSISTABLE),
	P_OLNS_O_ADD_ORIG_BILL_SER_IND1(PERSISTABLE),
	P_OLNS_O_ADD_ORIG_BILL_SER_IND2(PERSISTABLE), 
	P_OLNS_O_ORIG_IC_DIGITS(PERSISTABLE),
	P_OLNS_O_ORIG_INC_DIGITS(PERSISTABLE), 
	P_OLNS_O_FOREIGN_LANG_ID(PERSISTABLE),
	P_OLNS_O_GENERIC_NAME(PERSISTABLE),
	P_OLNS_O_GENERIC_NAME_AVAILABILITY(PERSISTABLE),
	P_OLNS_O_GENERIC_NAME_PRESENTATION(PERSISTABLE),
	P_OLNS_O_ALPHANUMERIC_STRING(PERSISTABLE),
	P_OLNS_O_DISALLOWED_CARD_ISSUER_CODE(PERSISTABLE), 
	P_OLNS_O_ORIG_LISTING_SERV_IND1(PERSISTABLE),
	P_OLNS_O_ACC_OWNER(PERSISTABLE),
	P_OLNS_O_BILING_SER_PROV(PERSISTABLE),
	P_OLNS_O_WIRELESS_SERVICES_ORIG_INDICATOR(PERSISTABLE),
	P_OLNS_SERVICEKEY_DIGITS_TYPE(PERSISTABLE),
	P_OLNS_O_ACG_CALLING_NUMBER(PERSISTABLE),
	//GETDATA Query Parameter
	GETDATA_QUERIED_NUM(PERSISTABLE),
	GETDATA_PRIMARY_SERVICE_REQUESTER(PERSISTABLE),
	GETDATA_PSRID_TYPE(PERSISTABLE),
	GETDATA_ACCOUNT_OWNER(PERSISTABLE),
	GETDATA_ADDITIONAL_ORIG_BILLING_SERVICE_INDICATORS(PERSISTABLE),
	GETDATA_ADDITIONAL_ORIG_THIRD_NUMBER_INDICATOR(PERSISTABLE),
	GETDATA_ADDITIONAL_ORIG_CREDIT_CARD_INDICATOR(PERSISTABLE),
	GETDATA_ADDITIONAL_ORIG_SPECIAL_BNS_INDICATOR(PERSISTABLE),
	GETDATA_ADDITIONAL_ORIG_SENTPAID_INDICATOR(PERSISTABLE),
	GETDATA_ADDITIONAL_ORIG_BILLING_SERVICE_SPARE_INDICATOR(PERSISTABLE),
	GETDATA_ALPHANUMERIC_STRING(PERSISTABLE),
	GETDATA_ALTERNATE_PREFERRED_IC(PERSISTABLE),
	GETDATA_BILLING_SERVICE_PROVIDER(PERSISTABLE),
	GETDATA_SERVICE_DENIAL_INDICATOR(PERSISTABLE),
	GETDATA_COLLECT_ACCEPTANCE_INDICATOR(PERSISTABLE),
	GETDATA_DIVERSION_ROUTING_NUMBER(PERSISTABLE),
	GETDATA_FOREIGN_LANGUAGE_IDENTIFIER(PERSISTABLE),
	GETDATA_GENERIC_NAME(PERSISTABLE),
	GETDATA_IC_INDICATORS(PERSISTABLE),
	GETDATA_PRIMARY_PREFERRED_IC_INDICATOR(PERSISTABLE),
	GETDATA_ALTERNATE_PREFERRED_IC_INDICATOR(PERSISTABLE),
	GETDATA_PREFERRED_INC_INDICATOR(PERSISTABLE),
	GETDATA_ILP_CIC_INDICATOR(PERSISTABLE),
	GETDATA_ILP_CIC(PERSISTABLE),
	GETDATA_INTERCEPT_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_BILLING_SERVICE_INDICATORS(PERSISTABLE),
	GETDATA_ORIG_COLLECT_BILLING_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_THIRD_NUMBER_BILLING_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_LOCAL_NONTOLL_CALL_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_CREDIT_CARD_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_FREE_DA_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_SPECIAL_BNS_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_SENTPAID_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_DACC_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_BILLING_SERVICE_SPARE_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_IC_INDICATORS(PERSISTABLE),
	GETDATA_ORIG_IC_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_INC_INDICATOR(PERSISTABLE),
	GETDATA_ORIG_IC(PERSISTABLE),
	GETDATA_ORIG_INC(PERSISTABLE),
	GETDATA_ORIG_LISTING_SERVICES_INDICATOR_1(PERSISTABLE),
	GETDATA_PREFERRED_INC(PERSISTABLE),
	GETDATA_PRIMARY_PREFERRED_IC(PERSISTABLE),
	GETDATA_RAO(PERSISTABLE),
	GETDATA_RECORD_STATUS_INDICATOR(PERSISTABLE),
	GETDATA_REFERRAL_NUMBER(PERSISTABLE),
	P_GETDATA_O_REF_NUM_TYPE(PERSISTABLE),
	GETDATA_SERVICE_OR_EQUIPMENT_INDICATOR(PERSISTABLE),
	GETDATA_THIRD_NUMBER_ACCEPTANCE_INDICATOR(PERSISTABLE),
	GETDATA_TREATMENT_INDICATOR(PERSISTABLE),
	GETDATA_WIRELESS_SERVICES_ORIG_INDICATOR(PERSISTABLE),
	GETDATA_WIRELESS_SERVICES_TERMINATING_INDICATOR(PERSISTABLE),
	GETDATA_PREFERRED_CODE_LIST(PERSISTABLE),
	GETDATA_TRUE_BILLING_NUMBER(PERSISTABLE),
	GETDATA_INVALID_TCAPID_LIST(PERSISTABLE),
	GETDATA_RECEIVED_TCAPID_LIST(PERSISTABLE),
	
	//GETDATA Response Parameters
	P_GETDATA_O_ACCOUNT_OWNER_ERR(PERSISTABLE),
	P_GETDATA_O_ACCOUNT_OWNER(PERSISTABLE),

	P_GETDATA_O_ADDITIONAL_ORIG_BILLING_SERVICE_INDICATORS_ERR(PERSISTABLE),
	P_GETDATA_O_ADDITIONAL_ORIG_BILLING_SERVICE_INDICATORS(PERSISTABLE),
	//	P_GETDATA_O_ADDITIONAL_ORIG_BILLING_SERVICE_INDICATORS1(PERSISTABLE),
	//	P_GETDATA_O_ADDITIONAL_ORIG_BILLING_SERVICE_INDICATORS2(PERSISTABLE),

	P_GETDATA_O_ADDITIONAL_ORIG_THIRD_NUMBER_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ADDITIONAL_ORIG_THIRD_NUMBER_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ADDITIONAL_ORIG_CREDIT_CARD_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ADDITIONAL_ORIG_CREDIT_CARD_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ADDITIONAL_ORIG_SPECIAL_BNS_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ADDITIONAL_ORIG_SPECIAL_BNS_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ADDITIONAL_ORIG_SENTPAID_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ADDITIONAL_ORIG_SENTPAID_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ADDITIONAL_ORIG_BILLING_SERVICE_SPARE_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ADDITIONAL_ORIG_BILLING_SERVICE_SPARE_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ALPHANUMERIC_STRING_ERR(PERSISTABLE),
	P_GETDATA_O_ALPHANUMERIC_STRING(PERSISTABLE),

	P_GETDATA_O_ALTERNATE_PREFERRED_IC_ERR(PERSISTABLE),
	P_GETDATA_O_ALTERNATE_PREFERRED_IC(PERSISTABLE),

	P_GETDATA_O_BILLING_SERVICE_PROVIDER_ERR(PERSISTABLE),
	P_GETDATA_O_BILLING_SERVICE_PROVIDER(PERSISTABLE),

	P_GETDATA_O_SERVICE_DENIAL_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_SERVICE_DENIAL_INDICATOR(PERSISTABLE),

	P_GETDATA_O_COLLECT_ACCEPTANCE_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_COLLECT_ACCEPTANCE_INDICATOR(PERSISTABLE),

	P_GETDATA_O_DIVERSION_ROUTING_NUMBER_ERR(PERSISTABLE),
	P_GETDATA_O_DIVERSION_ROUTING_NUMBER(PERSISTABLE),

	P_GETDATA_O_FOREIGN_LANGUAGE_IDENTIFIER_ERR(PERSISTABLE),
	P_GETDATA_O_FOREIGN_LANGUAGE_IDENTIFIER(PERSISTABLE),

	P_GETDATA_O_GENERIC_NAME_ERR(PERSISTABLE),
	P_GETDATA_O_GENERIC_NAME(PERSISTABLE),

	P_GETDATA_O_IC_INDICATORS_ERR(PERSISTABLE),
	P_GETDATA_O_IC_INDICATORS1(PERSISTABLE),
	P_GETDATA_O_IC_INDICATORS2(PERSISTABLE),

	P_GETDATA_O_PRIMARY_PREFERRED_IC_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_PRIMARY_PREFERRED_IC_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ALTERNATE_PREFERRED_IC_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ALTERNATE_PREFERRED_IC_INDICATOR(PERSISTABLE),

	P_GETDATA_O_PREFERRED_INC_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_PREFERRED_INC_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ILP_CIC_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ILP_CIC_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ILP_CIC_ERR(PERSISTABLE),
	P_GETDATA_O_ILP_CIC(PERSISTABLE),

	P_GETDATA_O_INTERCEPT_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_INTERCEPT_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_BILLING_SERVICE_INDICATORS_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_BILLING_SERVICE_INDICATORS(PERSISTABLE),
	//	P_GETDATA_O_ORIG_BILLING_SERVICE_INDICATORS1(PERSISTABLE),
	//	P_GETDATA_O_ORIG_BILLING_SERVICE_INDICATORS2(PERSISTABLE),
	//	P_GETDATA_O_ORIG_BILLING_SERVICE_INDICATORS3(PERSISTABLE),

	P_GETDATA_O_ORIG_COLLECT_BILLING_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_COLLECT_BILLING_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_THIRD_NUMBER_BILLING_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_THIRD_NUMBER_BILLING_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_LOCAL_NONTOLL_CALL_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_LOCAL_NONTOLL_CALL_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_CREDIT_CARD_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_CREDIT_CARD_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_FREE_DA_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_FREE_DA_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_SPECIAL_BNS_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_SPECIAL_BNS_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_SENTPAID_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_SENTPAID_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_DACC_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_DACC_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_BILLING_SERVICE_SPARE_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_BILLING_SERVICE_SPARE_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_IC_INDICATORS_ERR(PERSISTABLE),
	//	P_GETDATA_O_ORIG_IC_INDICATORS1(PERSISTABLE),
	//	P_GETDATA_O_ORIG_IC_INDICATORS2(PERSISTABLE),
	P_GETDATA_O_ORIG_IC_INDICATORS(PERSISTABLE), //collective orig ic indicators


	P_GETDATA_O_ORIG_IC_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_IC_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_INC_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_INC_INDICATOR(PERSISTABLE),

	P_GETDATA_O_ORIG_IC_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_IC(PERSISTABLE),

	P_GETDATA_O_ORIG_INC_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_INC(PERSISTABLE),

	P_GETDATA_O_ORIG_LISTING_SERVICES_INDICATOR_1_ERR(PERSISTABLE),
	P_GETDATA_O_ORIG_LISTING_SERVICES_INDICATOR_1(PERSISTABLE),

	P_GETDATA_O_PREFERRED_INC_ERR(PERSISTABLE),
	P_GETDATA_O_PREFERRED_INC(PERSISTABLE),

	P_GETDATA_O_PRIMARY_PREFERRED_IC_ERR(PERSISTABLE),
	P_GETDATA_O_PRIMARY_PREFERRED_IC(PERSISTABLE),

	P_GETDATA_O_RAO_ERR(PERSISTABLE),
	P_GETDATA_O_RAO(PERSISTABLE),

	P_GETDATA_O_RECORD_STATUS_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_RECORD_STATUS_INDICATOR(PERSISTABLE),

	P_GETDATA_O_REFERRAL_NUMBER_ERR(PERSISTABLE),
	P_GETDATA_O_REFERRAL_NUMBER(PERSISTABLE),

	P_GETDATA_O_SERVICE_OR_EQUIPMENT_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_SERVICE_OR_EQUIPMENT_INDICATOR(PERSISTABLE),

	P_GETDATA_O_THIRD_NUMBER_ACCEPTANCE_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_THIRD_NUMBER_ACCEPTANCE_INDICATOR(PERSISTABLE),

	P_GETDATA_O_TREATMENT_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_TREATMENT_INDICATOR(PERSISTABLE),

	P_GETDATA_O_WIRELESS_SERVICES_ORIG_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_WIRELESS_SERVICES_ORIG_INDICATOR(PERSISTABLE),

	P_GETDATA_O_WIRELESS_SERVICES_TERMINATING_INDICATOR_ERR(PERSISTABLE),
	P_GETDATA_O_WIRELESS_SERVICES_TERMINATING_INDICATOR(PERSISTABLE),

	P_GETDATA_O_PREFERRED_CODE_LIST_ERR(PERSISTABLE),
	P_GETDATA_O_PREFERRED_CODE_LIST(PERSISTABLE),

	P_GETDATA_O_TRUE_BILLING_NUMBER_ERR(PERSISTABLE),
	P_GETDATA_O_TRUE_BILLING_NUMBER(PERSISTABLE),
	P_GETDATA_O_ACG_QUERIED_NUM(PERSISTABLE),

	// CAMEL CAPv2 Specific Attributes
	P_CAP_MAX_CALL_PERIOD_DURATION(PERSISTABLE),
	P_CAP_RELEASE_IF_DURATION_EXCEED(PERSISTABLE),
	P_CAP_PARTY_TO_CHARGE(PERSISTABLE),

	// ACR Params
	P_CAP_ACR_TIME_IF_NO_TRAFFIC_SWITCH(PERSISTABLE),
	P_CAP_ACR_TIME_IF_TRAFFIC_SWITCH(PERSISTABLE),
	P_CAP_ACR_IS_LEG_ACTIVE(PERSISTABLE),

	P_CAP_CALLING_PARTYS_CATEGORY(PERSISTABLE),
	P_CAP_LOCATION_NUMBER(PERSISTABLE),
	P_CAP_EXTENSIONS(PERSISTABLE),
	P_CAP_BEARER_CAPABILITY(PERSISTABLE),
	P_CAP_EVENT_TYPE_BCSM(PERSISTABLE),
	P_CAP_IMSI(PERSISTABLE),
	P_CAP_LOCATION_INFORMATION(PERSISTABLE),              
	P_CAP_EXT_BASIC_SERVICE_CODE(PERSISTABLE),
	P_CAP_CALL_REFERENCE_NUMBER(PERSISTABLE),
	P_CAP_MSC_ADDRESS(PERSISTABLE),
	P_CAP_CALLED_PARTY_BCD_NUMBER(PERSISTABLE),
	P_CAP_TIME_AND_TIMEZONE(PERSISTABLE),

	//Provider Instruction Arg Parameters
	P_PI_O_CIC_SUPPORT(PERSISTABLE),
	//Connection Control Arg Parameters
	P_NETWORK_ROUTING_NUMBER(PERSISTABLE),

	//AC Query Specific Attributes
	P_MRS_COMP_LIST(NON_PERSISTABLE),
	P_SERVICE_TYPE(NON_PERSISTABLE),
	P_MRS_QTYPE(NON_PERSISTABLE),
	P_MR_SSN(NON_PERSISTABLE),
	P_MR_PC(NON_PERSISTABLE),
	P_MR_TT(NON_PERSISTABLE),
	P_MR_GT_DIGITS(NON_PERSISTABLE),
	P_MR_ROUTING_INDICATOR(NON_PERSISTABLE),
	RELAY_MSG (NON_PERSISTABLE),
	P_BEGIN_QOS(NON_PERSISTABLE),

	// for Triggering Criteria Rule
	P_TC_POINT_CODE(PERSISTABLE),
	P_TC_CALLING_PARTY(PERSISTABLE),
	P_TC_CALLED_PARTY(PERSISTABLE),
	P_TC_SSN(PERSISTABLE), 
	P_TC_CIC(PERSISTABLE), 
	P_TC_TRUNK_GROUP(PERSISTABLE),
	P_TC_SERVICE_KEY(PERSISTABLE),
	P_TC_OP_CODE(PERSISTABLE),
	P_TC_PROTOCOL(PERSISTABLE),
	P_TC_TRIGGERING_CRITERIA(PERSISTABLE),


	// diameter fields
	DIAMETER_IN_CCR_REQ(NON_PERSISTABLE), 
	DIAMETER_IN_CCR_RES(NON_PERSISTABLE),
	DIAMETER_REQ_AVP_LIST(NON_PERSISTABLE),
	DIAMETER_RES_AVP_LIST(NON_PERSISTABLE),
	DIAMETER_CCA_OUT_RETURN_CODE(NON_PERSISTABLE),
	DIAMETER_CCR_REQUESTED_ACTION(NON_PERSISTABLE),
	DIAMETER_RO_ROUTE_REMOTE_REALM(NON_PERSISTABLE),

	// ACG Parameters 
	ACG_SCP_OVERLOAD_CTRL_IND(NON_PERSISTABLE), 
	ACG_SMS_INIT_CTRL_IND(NON_PERSISTABLE), 
	ACG_NUM_OF_DIGITS(NON_PERSISTABLE), 
	ACG_GTA(NON_PERSISTABLE), 
	ACG_GAP_INTERVAL_TYPE(NON_PERSISTABLE), 
	ACG_TRANSLATION_TYPE(NON_PERSISTABLE), 
	ACG_GAP_DURATION(NON_PERSISTABLE), 
	ACG_GAP_INTERVAL_VALUE(NON_PERSISTABLE), 
	SEND_ACG(NON_PERSISTABLE), 
	ENUM_ZONE_QUERIED(NON_PERSISTABLE), 

	//Diameter AVPs
	DIAMETER_CCR_SESSION_ID(NON_PERSISTABLE),
	DIAMETER_DEST_REALM(NON_PERSISTABLE),
	DIAMETER_DEST_HOST(NON_PERSISTABLE),
	DIAMETER_ORIGIN_REALM(NON_PERSISTABLE),
	DIAMETER_ORIGIN_HOST(NON_PERSISTABLE), 
	DIAMETER_CC_REQUEST_NUMBER(NON_PERSISTABLE),
	DIAMETER_CC_REQUEST_TYPE(NON_PERSISTABLE), 
	DIAMETER_AUTH_APP_ID(NON_PERSISTABLE), 
	DIAMETER_SERVICE_CONTEXT_ID(NON_PERSISTABLE), 
	DIAMETER_USER_NAME(NON_PERSISTABLE), 
	DIAMETER_ORIG_STATE_ID(NON_PERSISTABLE), 
	DIAMETER_EVENT_TIMESTAMP(NON_PERSISTABLE), 
	DIAMETER_SERVICE_INFORMATION(NON_PERSISTABLE), 
	DIAMETER_PRECEDENCE(NON_PERSISTABLE), 
	DIAMETER_MULTI_SERVICE_CREDIT_CONTROL(NON_PERSISTABLE), 
	DIAMETER_SUBSCRIPTION_ID_TYPE(NON_PERSISTABLE),
	DIAMETER_SUBSCRIPTION_ID_DATA(NON_PERSISTABLE), 

	DIAMETER_RSU_CC_TIME(NON_PERSISTABLE),
	DIAMETER_RSU_CC_MONEY_VALUE_DIGITS(NON_PERSISTABLE), 
	DIAMETER_RSU_CC_MONEY_EXPONENT(NON_PERSISTABLE), 
	DIAMETER_RSU_CC_TOTAL_OCTETS(NON_PERSISTABLE), 
	DIAMETER_RSU_CC_INPUT_OCTETS(NON_PERSISTABLE), 
	DIAMETER_RSU_CC_OUTPUT_OCTETS(NON_PERSISTABLE),
	DIAMETER_RSU_CC_SERVICE_SPECIFIC_UNITS(NON_PERSISTABLE), 
	DIAMETER_RSU_CC_MONEY_CURRENCY_CODE(NON_PERSISTABLE),

	DIAMETER_FUI_FINAL_UNIT_ACTION(NON_PERSISTABLE), 
	DIAMETER_FUI_RESTRICTION_FILTER_RULE(NON_PERSISTABLE), 
	DIAMETER_FUI_FILTER_ID(NON_PERSISTABLE),
	DIAMETER_FUI_REDIRECT_ADDRESS_TYPE(NON_PERSISTABLE), 
	DIAMETER_FUI_REDIRECT_ADDRESS(NON_PERSISTABLE),

	DIAMETER_GSU_TARIFF_TIME_CHANGE(NON_PERSISTABLE),
	DIAMETER_GSU_CC_TIME(NON_PERSISTABLE),
	DIAMETER_GSU_CC_MONEY_VALUE_DIGITS(NON_PERSISTABLE), 
	DIAMETER_GSU_CC_MONEY_EXPONENT(NON_PERSISTABLE), 
	DIAMETER_GSU_CC_TOTAL_OCTETS(NON_PERSISTABLE), 
	DIAMETER_GSU_CC_INPUT_OCTETS(NON_PERSISTABLE), 
	DIAMETER_GSU_CC_OUTPUT_OCTETS(NON_PERSISTABLE),
	DIAMETER_GSU_CC_SERVICE_SPECIFIC_UNITS(NON_PERSISTABLE),
	DIAMETER_GSU_CC_MONEY_CURRENCY_CODE(NON_PERSISTABLE),
	DIAMETER_USU_CC_TIME(NON_PERSISTABLE), 

	DIAMETER_USU_REPORTING_REASON(NON_PERSISTABLE), 
	DIAMETER_USU_TARIFF_CHANGE_USAGE(NON_PERSISTABLE),
	DIAMETER_USU_CC_TOTAL_OCTETS(NON_PERSISTABLE), 
	DIAMETER_USU_CC_INPUT_OCTETS(NON_PERSISTABLE), 
	DIAMETER_USU_CC_OUTPUT_OCTETS(NON_PERSISTABLE), 
	DIAMETER_USU_CC_SERVICE_SPECIFIC_UNITS(NON_PERSISTABLE), 
	DIAMETER_USU_EVENT_CHARGING_TIMESTAMP(NON_PERSISTABLE),

	DIAMETER_ANN_IDENTIFIER(NON_PERSISTABLE), 
	DIAMETER_ANN_TIME_INDICATOR(NON_PERSISTABLE), 
	DIAMETER_ANN_QUOTA_INDICATOR(NON_PERSISTABLE), 
	DIAMETER_ANN_PLAY_ALTERNATIVE(NON_PERSISTABLE), 
	DIAMETER_ANN_ORDER(NON_PERSISTABLE), 
	DIAMETER_ANN_PRIVACY_INDICATOR(NON_PERSISTABLE),
	DIAMETER_ANN_PLANGUAGE(NON_PERSISTABLE), 
	DIAMETER_ANN_VAR_PART_ORDER(NON_PERSISTABLE), 
	DIAMETER_ANN_VAR_PART_TYPE(NON_PERSISTABLE), 
	DIAMETER_ANN_VAR_PART_VALUE(NON_PERSISTABLE), 

	DIAMETER_VALIDITY_TIME(NON_PERSISTABLE), 
	DIAMETER_TIME_QUOTA_THRESHOLD(NON_PERSISTABLE), 

	DIAMETER_COST_INFO_VALUE_DIGITS(NON_PERSISTABLE), 
	DIAMETER_COST_INFO_EXPONENT(NON_PERSISTABLE), 
	DIAMETER_COST_INFO_CURRENCY_CODE(NON_PERSISTABLE), 
	DIAMETER_COST_INFO_COST_UNIT(NON_PERSISTABLE), 

	DIAMETER_CREDIT_CTRL_FAILURE_HANDLING(NON_PERSISTABLE), 
	DIAMETER_DEBIT_CTRL_FAILURE_HANDLING(NON_PERSISTABLE), 
	DIAMETER_CC_SESSION_FAILOVER(NON_PERSISTABLE), 
	P_LEG_DIAMETER_STATE(PERSISTABLE),
	DIAMETER_IN_CCA_REQ_TYPE(NON_PERSISTABLE),

	//diamter AVP ends here

	// CAPV2 bearer cap
	CAP_BEARER_CAP_INFO_TRANSFER_CAP(PERSISTABLE),
	CAP_BEARER_CAP_INFO_TRANSFER_RATE(PERSISTABLE),
	CAP_BEARER_CAP_USER_INFO_LAYER1(PERSISTABLE),
	CAP_BEARER_CAP_USER_INFO_LAYER2(PERSISTABLE),
	CAP_BEARER_CAP_USER_INFO_LAYER3(PERSISTABLE),

	// CAPV2 IMSI
	CAP_IMSI_COUNTRY_CODE(PERSISTABLE),
	CAP_IMSI_NETWORK_CODE(PERSISTABLE),
	CAP_IMSI_AREA_CODE(PERSISTABLE),


	// CAPV2 Location Number
	CAP_LOCATION_NUM(PERSISTABLE),

	// CAPV2 Location Information
	CAP_LOCATION_INFO_VLR_NUMBER(PERSISTABLE),
	CAP_LOCATION_INFO_VLR_NOA(PERSISTABLE),
	CAP_LOCATION_INFO_MSISDN(PERSISTABLE),
	CAP_LOCATION_INFO_COUNTRY_CODE(PERSISTABLE),

	//// CAPV2 Reference Num
	CAP_CALL_REFERENCE_NUM(PERSISTABLE),

	// CAP V2 MSC Address
	CAP_MSC_ADDRESS_NOA(PERSISTABLE), 
	CAP_MSC_ADDRESS_MSISDN(PERSISTABLE), 
	CAP_MSC_ADDRESS_COUNTRY_CODE(PERSISTABLE),

	// CAP V2 Timezone
	CAP_TIME_AND_TIMEZONE(PERSISTABLE), 
	CAP_CELL_GLOBAL_ID(PERSISTABLE), 
	
	//SMPP_DELIVERY
	SMPP_DELIVERY_RESPONSE_CODE(NON_PERSISTABLE),
	SMPP_DELIVERY_RESPONSE_STATUS(NON_PERSISTABLE),
	SMPP_DELIVERY_MSISDN(NON_PERSISTABLE),
	SMPP_SUBMIT_DATE_TIME(NON_PERSISTABLE),
	SMPP_DELVERY_DATE_TIME(NON_PERSISTABLE),
	SMPP_SUBMIT_SM_ID(NON_PERSISTABLE),
	SMPP_DELIVER_SM_ID(NON_PERSISTABLE),
	//SMPP
	SMPP_SRC_PHONE_NUMBER(NON_PERSISTABLE),
	SMPP_DEST_PHONE_NUMBER(NON_PERSISTABLE), 
	SMPP_SHORT_MESSAGE(NON_PERSISTABLE),
	SMPP_SOURCE_NPI(NON_PERSISTABLE),
	SMPP_SOURCE_TON(NON_PERSISTABLE),
	SMPP_DEST_NPI(NON_PERSISTABLE),
	SMPP_DEST_TON(NON_PERSISTABLE),
	SMPP_LANGUAGE(NON_PERSISTABLE),
	SMPP_STATUS(NON_PERSISTABLE),
	SMPP_COMMAND_STATUS_LIST(NON_PERSISTABLE),
	NP_PANI_HEADER(NON_PERSISTABLE),
	NP_PANI_CELL_ID(NON_PERSISTABLE), 
	NP_PANI_ACCESS_TYPE(NON_PERSISTABLE), 
	P_PANI_ADD_ON_PART(NON_PERSISTABLE), 


	//CCB Attriute
	CCB_GROUP_TIMESTAMP_ID(NON_PERSISTABLE),
	CCB_GROUP_LIMIT(NON_PERSISTABLE),
	CCB_NUMBER_LIMIT(NON_PERSISTABLE),
	CCB_EMAIL_SUBJECT(NON_PERSISTABLE),
	CCB_EMAIL_CONTENT(NON_PERSISTABLE),
	CCB_EMAIL_RECIEPIENTS(NON_PERSISTABLE),
	CCB_EMAIL_CALL_LIMIT(NON_PERSISTABLE),
	CCB_EMAIL_THRESHOLD(NON_PERSISTABLE),
	CCB_SEND_EMAIL_NOTIFICATION(NON_PERSISTABLE),
	// INAP attributes
	NP_RELEASE_REASON_VALUE(NON_PERSISTABLE), 

	DIAMETER_IMS_INFO_EVENT_TYPE_EXPIRES(NON_PERSISTABLE), 
	DIAMETER_IMS_INFO_NODE_FUNCTIONALITY(NON_PERSISTABLE), 
	DIAMETER_IMS_INFO_ROLE_OF_NODE(NON_PERSISTABLE), 
	DIAMETER_IMS_USER_SESSION_ID(NON_PERSISTABLE), 
	DIAMETER_IMS_CALLING_PARTY_ADDRESS(NON_PERSISTABLE),
	DIAMETER_IMS_CALLED_PARTY_ADDRESS(NON_PERSISTABLE), 
	DIAMETER_IMS_INFO_EVENT_TYPE_EVENT(NON_PERSISTABLE),
	DIAMETER_IMS_INFO_EVENT_TYPE_SIP_METHOD(NON_PERSISTABLE),
	DIAMETER_IMS_SIP_REQUEST_TIMESTAMP(NON_PERSISTABLE), 
	DIAMETER_IMS_SIP_REQUEST_TIMESTAMP_FRACTION(NON_PERSISTABLE),
	DIAMETER_IMS_SIP_RESPONSE_TIMESTAMP(NON_PERSISTABLE), 
	DIAMETER_IMS_SIP_RESPONSE_TIMESTAMP_FRACTION(NON_PERSISTABLE),
	DIAMETER_MSCC_SERVICE_IDENTIFIER(NON_PERSISTABLE),
	DIAMETER_MSCC_RESULT_CODE(NON_PERSISTABLE),
	DIAMETER_AOC_COST_INFO_ACCM_COST_VALUE_DIGITS(NON_PERSISTABLE), 
	DIAMETER_AOC_COST_INFO_ACCM_COST_EXPONENT(NON_PERSISTABLE), 
	DIAMETER_AOC_COST_INFO_CURRENCY_CODE(NON_PERSISTABLE),
	DIAMETER_ANN_INST_ANN_NUMBER(NON_PERSISTABLE), 
	DIAMETER_ANN_INST_ANN_ORDER(NON_PERSISTABLE), 
	DIAMETER_ANN_INST_ANN_TYPE(NON_PERSISTABLE), 
	DIAMETER_IMS_INFO_TIME_STAMP(NON_PERSISTABLE), 
	DIAMETER_TERMINATION_CAUSE(NON_PERSISTABLE), 
	NP_HTTP_JSON_CONTENT_RECEIVED(NON_PERSISTABLE),
	NP_HTTP_RESPONSE_CONTENT(NON_PERSISTABLE),
	NP_HTTP_RESPONSE_CONTENT_TYPE(NON_PERSISTABLE), NP_HTTP_RESPONSE_CODE(NON_PERSISTABLE),


	//MAP ATI send Interrogation specific fields	
	MAP_ATI_DOMAIN_TYPE(NON_PERSISTABLE),
	MAP_ATI_CURRENT_LOCATION(NON_PERSISTABLE),
	MAP_ATI_MSISDN(NON_PERSISTABLE),
	MAP_ATI_GSM_SCF_ADDRESS(NON_PERSISTABLE),

	// diameter sh attributes
	MAP_UDR_CURRENT_LOCATION(NON_PERSISTABLE),
	MAP_UDR_MSISDN(NON_PERSISTABLE),
	MAP_UDR_DOMAIN_TYPE(NON_PERSISTABLE),
	MAP_UDR_DESTINATION_REALM(NON_PERSISTABLE),
	

	// Outgoing dialogue
	P_SERVICE_KEY(PERSISTABLE),
	// ROuting Number received after external query
	P_EXTERNAL_RN(PERSISTABLE),

	NP_EXTENSION_PARAMETER(PERSISTABLE),
	NP_EXTENSION_PARAMETER_IDENTIFIER(PERSISTABLE), 
	P_SERVD_USER_SESS_CASE(NON_PERSISTABLE), 
	P_SERVD_USER_USERPART(NON_PERSISTABLE),
	P_SERVD_USER_PRIORITY(NON_PERSISTABLE),

	//CAIN
	CAIN_SERV_TRANSLATION_SCHEME(NON_PERSISTABLE),
	CAIN_NETWORK_BUSY_ACTION (NON_PERSISTABLE),
	CAIN_BILLING_NUMBER(NON_PERSISTABLE),
	CAIN_TREATMENT_CODE(NON_PERSISTABLE),
	ACCOUNT_CODE(NON_PERSISTABLE), 
	ACCOUNT_CODE_RESULT(NON_PERSISTABLE), 
	NP_UDA_VISITED_PLMN_ID(NON_PERSISTABLE),

	//MAP ATI dest SUA
	NP_DIALOUT_DEST_PC(NON_PERSISTABLE),
	NP_DIALOUT_DEST_SSN(NON_PERSISTABLE),
	NP_DIALOUT_DEST_TRANS_TYPE(NON_PERSISTABLE),
	NP_DIALOUT_DEST_GT_DIGITS(NON_PERSISTABLE),
	NP_DIALOUT_DEST_ROUTING_IND(NON_PERSISTABLE), 
	NP_DIALOUT_DEST_GT_IND(NON_PERSISTABLE),
	NP_MAP_QUERY_TYPE(NON_PERSISTABLE),
	NP_MAP_MSISDN(NON_PERSISTABLE),
	NP_MAP_IMSI(NON_PERSISTABLE),
	NP_MAP_SSEVENT_CODE(NON_PERSISTABLE),
		// GR533 FIelds 
	GR533_ACG_CONTROL_CAUSE_IND(NON_PERSISTABLE),
	
	//TR533 Attributes start
	P_TR533_CARRIER1(PERSISTABLE),
	PI_TR533_CARRIER1(NON_PERSISTABLE), 
	P_PI_TR533_O_CIC_SUPPORT1(PERSISTABLE),
	P_TR533_DESTINATION_NUMBER1(PERSISTABLE),
	PI_TR533_AMA_CALLTYPE1(NON_PERSISTABLE),
	P_TR533_FEATURE_TYPE_INDICATOR1(PERSISTABLE),
	P_TR533_NO_ANSWER_TIME1(PERSISTABLE),
	P_TR533_SPECIAL_ROUTING1(PERSISTABLE),
	
	P_TR533_CARRIER2(PERSISTABLE),
	PI_TR533_CARRIER2(NON_PERSISTABLE), 
	P_PI_TR533_O_CIC_SUPPORT2(PERSISTABLE),
	P_TR533_DESTINATION_NUMBER2(PERSISTABLE),
	PI_TR533_AMA_CALLTYPE2(NON_PERSISTABLE),
	P_TR533_FEATURE_TYPE_INDICATOR2(PERSISTABLE),
	P_TR533_NO_ANSWER_TIME2(PERSISTABLE),
	P_TR533_SPECIAL_ROUTING2(PERSISTABLE),
	
	P_TR533_CARRIER3(PERSISTABLE),
	PI_TR533_CARRIER3(NON_PERSISTABLE), 
	P_PI_TR533_O_CIC_SUPPORT3(PERSISTABLE),
	P_TR533_DESTINATION_NUMBER3(PERSISTABLE),
	PI_TR533_AMA_CALLTYPE3(NON_PERSISTABLE),
	P_TR533_FEATURE_TYPE_INDICATOR3(PERSISTABLE),
	P_TR533_NO_ANSWER_TIME3(PERSISTABLE),
	P_TR533_SPECIAL_ROUTING3(PERSISTABLE),
	
	P_TR533_CARRIER4(PERSISTABLE),
	PI_TR533_CARRIER4(NON_PERSISTABLE), 
	P_PI_TR533_O_CIC_SUPPORT4(PERSISTABLE),
	P_TR533_DESTINATION_NUMBER4(PERSISTABLE),
	PI_TR533_AMA_CALLTYPE4(NON_PERSISTABLE),
	P_TR533_FEATURE_TYPE_INDICATOR4(PERSISTABLE),
	P_TR533_NO_ANSWER_TIME4(PERSISTABLE),
	P_TR533_SPECIAL_ROUTING4(PERSISTABLE),
	// disconnect leg id 
	DISCONNECT_LEGID(NON_PERSISTABLE),
	NP_UDA_RESULT_DESC(NON_PERSISTABLE),

	P_ISUP_OLEC_CIC(PERSISTABLE),
	P_ISUP_CHARGING_AREA(PERSISTABLE),
	P_ISUP_ADD_CLG_PTY_CAT1(PERSISTABLE),
	P_ISUP_ADD_CLG_PTY_CAT2(PERSISTABLE),
	P_ISUP_BEARER_CAP(PERSISTABLE),
	P_ISUP_CPC(PERSISTABLE),
	P_ISUP_CAUSE_CODE(PERSISTABLE),
	P_ISUP_AT_SUB_ADDR_INFO(PERSISTABLE),
	P_ISUP_CLG_PTY_NOA_INT(PERSISTABLE),
	P_ISUP_CLG_PTY_PRESENTATION_INDICATOR_INT(PERSISTABLE),
	P_ISUP_SRC_ISDN_ACCESS_IND_INT(PERSISTABLE),
	P_ISUP_DSTN_INTER_NW_IND_INT(PERSISTABLE),
	P_ISUP_TLEC(PERSISTABLE),
	P_CHARGING_AREA(PERSISTABLE),
	P_PID(PERSISTABLE),
	P_OLEC_IOI(PERSISTABLE),
	//Force Call cleanup 
	FORCE_CALL_CLEANUP_SESSION_ID(NON_PERSISTABLE),
	FORCE_CALL_CLEANUP_APP_ID(NON_PERSISTABLE),

	//  UDTS
	NP_SEND_UDTS(NON_PERSISTABLE),
	// Ss7 error code 
	NP_ERROR_CODE(NON_PERSISTABLE),
	// TNSI in Return result SUAS shoudl not be swaped which inc does in case SUA not specified
	P_SEND_SUA_AS_RECEIVED(PERSISTABLE), 
	NP_UDA_EXP_RESULT_CODE(PERSISTABLE),
	NP_UDA_EXP_RESULT_DESC(PERSISTABLE),
	

	NP_CALLING_PC(NON_PERSISTABLE),
	NP_CALLING_SSN(NON_PERSISTABLE),
	NP_CALLING_TRANS_TYPE(NON_PERSISTABLE),
	NP_CALLING_GT_DIGITS(NON_PERSISTABLE),
	NP_CALLING_ROUTING_IND(NON_PERSISTABLE), 
	NP_CALLING_GT_IND(NON_PERSISTABLE),
	
	
	NP_CALLED_PC(NON_PERSISTABLE),
	NP_CALLED_SSN(NON_PERSISTABLE),
	NP_CALLED_TRANS_TYPE(NON_PERSISTABLE),
	NP_CALLED_GT_DIGITS(NON_PERSISTABLE),
	NP_CALLED_ROUTING_IND(NON_PERSISTABLE), 
	NP_CALLED_GT_IND(NON_PERSISTABLE),

	//TNSI MTP3 data point code
	MTP3_DPC(PERSISTABLE), 
	MTP3_OPC(PERSISTABLE), 
	DIAMETER_IMS_TERMINATING_IOI(NON_PERSISTABLE), 
	DIAMETER_IMS_ACCESS_NETWORK_INFO(NON_PERSISTABLE),
	
	
	P_AMP1_ALERT_CALL(PERSISTABLE),
	P_AMP1_AMA_TREATMENT(PERSISTABLE),
	P_AMP1_CLOG_LEVEL(PERSISTABLE),
    P_AMP1_CLOG_SN(PERSISTABLE),
    P_AMP1_NULL_IND(PERSISTABLE),
    P_AMP1_TIME(PERSISTABLE),
    P_AMP1_DATE(PERSISTABLE),
    P_AMP_TIME(PERSISTABLE), //contains only HHMM for amp1
    P_AMP1_TIME_YEAR(PERSISTABLE),
    P_AMP_CURRENT_TIME_STAMP (PERSISTABLE),
    
    P_AMP2_CLOG_SQNNO(PERSISTABLE),
    P_AMP2_CLOG_REP_IND(PERSISTABLE),
    P_AMP2_CALL_PROG_IND(PERSISTABLE),
    P_AMP2_TEST_REQ_IND(PERSISTABLE),
    P_AMP2_SVC_PROV_ID(PERSISTABLE),
    P_AMP2_CLOG_NAME(PERSISTABLE),
    P_AMP2_AIN_SPEC_ID(PERSISTABLE),
    P_AMP2_AIN_ISDN_DEVICE_ID(PERSISTABLE),
    
    //added node name & clog seq name with static value as 0
    P_AMP_NODE_NAME(PERSISTABLE), //AMP2
    P_AMP_CLOG_SEQ_NAME(PERSISTABLE), //AMP2
    
    // GDI attributes
 	GDI_RECIEVER_ID(NON_PERSISTABLE),
 	GDI_DIALLED_NUMBER(NON_PERSISTABLE),
 	GDI_CALLING_NUMBER(NON_PERSISTABLE),
 	
 	GDI_APP_ID(NON_PERSISTABLE),
 	GDI_NAME(NON_PERSISTABLE),
 	
 	GDI_RESPONSE_DESTINATION_NUM(NON_PERSISTABLE),
 	GDI_RESPONSE_STATUS(NON_PERSISTABLE),
 	GDI_RESPONSE_ORIG_TRANS_ID(NON_PERSISTABLE),
    //ReturnOption 
    P_RETURN_OPTION(PERSISTABLE),
    P_RETURN_OPTION_REASON(PERSISTABLE),
    DIAMETER_IMS_REQUESTED_PARTY_ADDRESS(PERSISTABLE), 
    DIAMETER_UDR_SENT_TIMESTAMP(PERSISTABLE), 
    DIAMETER_UDA_RECEIVED_TIMESTAMP(PERSISTABLE),
    DIAMETER_IMS_SDP_MEDIA_NAME(NON_PERSISTABLE), 
    DIAMETER_IMS_CHARGING_IDENTIFIER(NON_PERSISTABLE), 
    DIAMETER_IMS_CAUSE_CODE(NON_PERSISTABLE),
    MAP_ATI_REQ_SENT_TIMESTAMP(NON_PERSISTABLE),
    MAP_ATI_RES_RECEIVED_TIMESTAMP(NON_PERSISTABLE),
    P_SEQUENCE_CONTROL(PERSISTABLE),
	P_MESSAGE_PRIORITY(PERSISTABLE),
	CD_PTY_NO_PC(NON_PERSISTABLE),
	CG_PTY_NO_PC(NON_PERSISTABLE),
    P_SEND_CALLING_PARTY(NON_PERSISTABLE);
	private PersistanceType persistanceType;
	LegDataAttributes(PersistanceType persistanceType) {
		this.persistanceType = persistanceType;
	}
	public PersistanceType getPersistanceType(){
		return this.persistanceType;
	}
}
